

name: Docset Build and Publish
on: 
  push:
    tags:
      - "*"


jobs:
  build-and-publish:
    runs-on: ubuntu-18.04
    steps:
      - name: Prepare
        uses: actions/setup-node@v2
        with:
            node-version: '12'
      - run: sudo npm_config_user=root npm install -g @cc12703m/mddocsetbuilder@1.5.1


      - name: Checkout
        uses: actions/checkout@v2
        with:
            path: './source'


      - name: Build Docset
        run: mddocsetbuilder ./source -o ./out -n learning_note -p tgz 
        working-directory: ${{ github.workspace }}


      - name: Update to release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: Release Document
          draft: false
          prerelease: false
      - id: update_release
        uses: xresloader/upload-to-github-release@v1
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: './out/learning_note.docset.tgz'
          release_id: ${{ steps.create_release.outputs.id }}
          overwrite: true
          draft: false
          prerelease: false
          verbose: true
      - run: echo $REL_URL
        env:
          REL_URL: ${{ steps.update_release.outputs.release_url}}
        
