

name: Docset Build and Publish
on: 
  push:
    branches:
      - main


jobs:
  build-and-publish:
    runs-on: ubuntu-18.04
    steps:
      - name: Prepare
        uses: actions/setup-node@v2
        with:
            node-version: '12'
      - run: npm install @cc12703m/mddocsetbuilder@1.3.0

      - name: Checkout
        uses: actions/checkout@v2
        with:
            path: './source'

      - name: Build Docset
        run: mddocsetbuilder ./source -o ./out -n learning_note -p tgz 
